### PR TITLE
some scribbles

### PR DESCRIPTION
**Pull request by job**

### CODE REVIEW

**Review by randyqx — COMMENTED** [review]
sorry to quibble, but i think of "pipeline" as being "|".  and "supply chain" is a popular and eye-catching phrase this season. :)

if this about all rpki data or just rov?  i can go either way on that.

**Review by randyqx — COMMENTED** [review]
you don't like stressing that it goes all teh way to routers?

**Comment by job** [comment]
merge this and we'll change pipeline back to supply chain

**Comment by job** [comment]
> you don't like stressing that it goes all teh way to routers?

what line are you referring to?

**Review by randyqx — APPROVED** [review]

**Review by randyqx — COMMENTED** [review]
it could be an iBGP-only router

"publication had near immediate" is not correct american

"validator" is a marketing term which i believe is not in the RFCs

it's "publication points" not "services"

"expedient" infers that it is fast/good, while i think you mean the opposite.

**Review by randyqx — COMMENTED** [review]
RPKI timing extends to teh Up/Down protocol, BPKI, ...  it is specifically ROV which we are discussing

**Comment by job** [comment]
I'm not sure which github workflow you follow... can you elaborate on how i should submit proposed text phrases?

**Pull request closed without merging**
